name: Ask a question
description: Questions about using or running Mink.
title: "[question] "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Config, code, or output that helps answer it. Optional.
      render: text
